#ifndef __ERROR_H__
#define __ERROR_H__

#define OPEN_TEM_DEV_ERROR 1000
#define IOCTRL_GET_TEM_ERROR 1001

#define OPEN_WET_DEV_ERROR {}

#define OPEN_LIGHT_VALUE_ERROR 1
#define READ_LIGHT_VALUE_ERROR 2
#define OPEN_LIGHT_SCALE_ERROR 3
#define READ_LIGHT_SCALE_ERROR 4
#define GET_LIGHT_VALUE_ERROR 5
#define GET_LIGHT_SCALE_ERROR 6

#define OPEN_OLED_DEV_ERROR 7
#define WRITE_OLED_ERROR 8

#define OPEN_EEPROM_DEV_ERROR 9
#define WRITE_EEPROM_ERROR 10
#define READ_EEPROM_ERROR 11

#endif